version: '3'

services:
    postgres:
        container_name: lfdc_postgres_local
        image: "postgres:15.2-alpine"
        user: postgres
        environment:
            - POSTGRES_USER=lfdc_ms_local
            - POSTGRES_PASSWORD=lfdc_ms_local
            - POSTGRES_DB=lfdc_ms_local
        ports:
        - 5432:5432
        volumes: 
        - postgres_data:/var/lib/postgresql/data
    minio:
        image: docker.io/bitnami/minio:2023
        container_name: lfdc_minio_local
        environment:
            - MINIO_ROOT_USER=lfdc_ms_local
            - MINIO_ROOT_PASSWORD=lfdc_ms_local
        ports:
        - '9000:9000'
        - '9001:9001'
        volumes:
        - 'minio_data:/bitnami/minio/data'

volumes:
    postgres_data:
        driver: local
    minio_data:
        driver: local